#pragma once

#define SCREEN_MANAGER_SWITCH_SCREEN_EVENT ALLEGRO_GET_EVENT_TYPE('L','v','l','S')
#define GAME_OVER_EVENT ALLEGRO_GET_EVENT_TYPE('G','m','O','v')
#define GAME_WON_EVENT ALLEGRO_GET_EVENT_TYPE('G','m','W','n')
#define PLAY_MUSIC_TRACK ALLEGRO_GET_EVENT_TYPE('M','U','S','C')
#define PLAY_SOUND_EFFECT ALLEGRO_GET_EVENT_TYPE('S','N','D','F')
#define STOP_ALL_MUSIC_AND_SOUND_EFFECTS_EVENT ALLEGRO_GET_EVENT_TYPE('S','t','A','l')



