#pragma once


#define SCREEN_TITLE_SCREEN "TITLE_SCREEN"
#define SCREEN_GAMEPLAY_SCREEN "GAMEPLAY_SCREEN"
#define SCREEN_GAME_OVER_SCREEN "GAME_OVER_SCREEN"
#define SCREEN_GAME_WON_SCREEN "GAME_WON_SCREEN"


