#pragma once


#include <vector>


class AudioRepositoryElement
{
public:
   std::string filename;
   bool loop;
};


#define TITLE_SCREEN_MUSIC "TITLE_SCREEN_MUSIC"
#define LEVEL_1_MUSIC "LEVEL_1_MUSIC"
#define GAME_OVER_SCREEN_MUSIC "GAME_OVER_SCREEN_MUSIC"
#define GAME_WON_SCREEN_MUSIC "GAME_WON_SCREEN_MUSIC"
#define FINAL_BOSS_MUSIC "FINAL_BOSS_MUSIC"
#define PLAYER_SHOOT_BULLET_SOUND_EFFECT "PLAYER_SHOOT_BULLET_SOUND_EFFECT"
#define ENEMY_TAKES_HIT_SOUND_EFFECT "ENEMY_TAKES_HIT_SOUND_EFFECT"
#define ENEMY_EXPLOSION_SOUND_EFFECT "ENEMY_EXPLOSION_SOUND_EFFECT"
#define BULLET_DEFLECTED_SOUND_EFFECT "BULLET_DEFLECTED_SOUND_EFFECT"


//enum music_track_t
//{
   //TITLE_SCREEN_MUSIC,
   //LEVEL_1_MUSIC,
   //GAME_OVER_SCREEN_MUSIC,
   //GAME_WON_SCREEN_MUSIC,
   //FINAL_BOSS_MUSIC,

   //PLAYER_SHOOT_BULLET_SOUND_EFFECT,
   //ENEMY_TAKES_HIT_SOUND_EFFECT,
   //ENEMY_EXPLOSION_SOUND_EFFECT,
   //BULLET_DEFLECTED_SOUND_EFFECT,
//};

