#pragma once


#define SCREEN_MANAGER_SWITCH_SCREEN_EVENT ALLEGRO_GET_EVENT_TYPE('L','v','l','S')
#define INCREASE_PLAYER_SCORE_EVENT ALLEGRO_GET_EVENT_TYPE('I','P','l','S')
#define SPAWN_POWER_UP_EVENT ALLEGRO_GET_EVENT_TYPE('S','p','n','P')
#define PLAYER_DRAGON_GETS_SPEED_BOOST_EVENT ALLEGRO_GET_EVENT_TYPE('G','t','S','P')

