#pragma once


#define SCREEN_MANAGER_SWITCH_SCREEN_EVENT ALLEGRO_GET_EVENT_TYPE('L','v','l','S')
#define INCREASE_PLAYER_SCORE_EVENT ALLEGRO_GET_EVENT_TYPE('I','P','l','S')

#define SPAWN_EXTRA_LIFE_POWER_UP_EVENT ALLEGRO_GET_EVENT_TYPE('S','p','L','f')
#define SPAWN_SHIELD_BOOST_POWER_UP_EVENT ALLEGRO_GET_EVENT_TYPE('S','p','S','h')
#define SPAWN_BULLET_BOOST_POWER_UP_EVENT ALLEGRO_GET_EVENT_TYPE('S','p','B','l')
#define SPAWN_SPEED_BOOST_POWER_UP_EVENT ALLEGRO_GET_EVENT_TYPE('S','p','S','p')
#define SPAWN_OPTION_BOOST_POWER_UP_EVENT ALLEGRO_GET_EVENT_TYPE('S','p','O','p')

#define PLAYER_DRAGON_GETS_EXTRA_LIFE_EVENT ALLEGRO_GET_EVENT_TYPE('G','t','L','f')
#define PLAYER_DRAGON_GETS_SHIELD_BOOST_EVENT ALLEGRO_GET_EVENT_TYPE('G','t','S','h')
#define PLAYER_DRAGON_GETS_BULLET_BOOST_EVENT ALLEGRO_GET_EVENT_TYPE('G','t','B','l')
#define PLAYER_DRAGON_GETS_SPEED_BOOST_EVENT ALLEGRO_GET_EVENT_TYPE('G','t','S','p')
#define PLAYER_DRAGON_GETS_OPTION_BOOST_EVENT ALLEGRO_GET_EVENT_TYPE('G','t','O','p')

